### ISSUE TITLE
Upload many pictures to a Jerry

### ISSUE THREAD

**Issue by Em-AK** [JerryDIT/adoptajerry#15]
As a maker I want to upload many pictures to my Jerry in order to document my Jerry according to the [community guidelines](https://docs.google.com/presentation/d/1XnoxAEcpgvme9ytHeSsPLn65bVwllHLr2VJsNktKhWo/edit#slide=id.p)

**Comment by Openizer** [comment]
10 is good

**Comment by Em-AK** [comment]
Its unlimited baby !

The upload is working, I need to try it on staging then deploy to production.
