### ISSUE TITLE
Make the pad responsive

### ISSUE THREAD

**Issue by Em-AK** [JerryDIT/adoptajerry#23]
Afficher le pad avec une dimenssion adaptée sur les écrans small et medium.

/!\ Intégrer plusieures iframes dans la même page en les cachant/affichant en fonction du contexte fait planter etherpad ;)

### Pistes d'implémentation
1. [détecter la taille de la fenêtre avec javascript](http://stackoverflow.com/questions/4477648/rails-3-how-to-store-screen-resolution)
2. ajuster la hauteur et la largeur de l'iframe adaptée en javascript

ou 
1. detecter la taille de la fenêtre
2. stocker la valeur dans la session via une hidden form
3. appeler l'iframe à la bonne taille dans la vue en fonction de ce paramètre

**Comment by Openizer** [comment]
TO KILL
