### ISSUE TITLE
[POC21] Update "Register your Jerry"

### ISSUE THREAD

**Issue by Openizer** [JerryDIT/adoptajerry#31]
[page principale] Remplacer "Register" par "Upload your Jerry Computer" 
+ |soustitre| "Each Jerry is unique, please introduce him or her to the family!"  

[page "Upload your Jerry"] Diviser le processus en 4 écrans-étapes : 

I) Tell the world about the story of your Jerry Computer 
*Choose a nice name :)  [Champ texte libre]
*Where the components come from? [Champ texte libre]
*What are you proud of about your Jerry? [Champ texte libre]
*How your Jerry came to the world? [Champ texte libre] 
*OPTION : Please fill this form to upload the info of your Jerry workshop [insertion lien https://docs.google.com/forms/d/1Vd7SCMPFZPxhgdT6J0e9hIRMisbzRBrsU9AqEhu2gKY/viewform]

II) Everyone is curious about the Organs of your Jerry Computer! [Champ texte libre]
* What is the hardware configuration? [champ Organ existant]
* What do you need to finish or improve it? [Exemple en sous-titre "I whish [a persona] could [do something] in order to [expected value]. I need [skill] ex: I cant install LinuxMint because of Harddrive troubles. I need new hardrive or hardware fixing skills." + Champ texte libre]

III) We all want to know about the free|open source Skills of your Jerry Computer! [Champ texte libre]
* What is the software configuration ? [sous-titre: please insert links] + [champ Skills existant]
* What do you need to finish or improve it? [Exemple en sous-titre "I whish [a persona] could [do something] in order to [expected value]. I need [skill] ex: I whish a coworker could remotely upload the tunes he likes in order to make them available to the whole space. I need web devops skills" + Champ texte libre]

iV) Each Jerry was made to accomplish a Mission. [Champ texte libre]
*Who use your Jerry? [Champ texte libre]
*How your Jerry help them? [Champ texte libre]
*What do you need to finish or improve it? [Champ texte libre]

**Comment by ekkans** [comment]
I/ Bio
II/ Organs
III/ Skills
IV/ Mission

**Comment by ekkans** [comment]
Where did the components come from?
What makes you proud in your Jerry?
How did your Jerry come to the world?
Who uses your Jerry?
How does your Jerry help them?
