### ISSUE TITLE
[POC21] Update page "build your jerry"

### ISSUE THREAD

**Issue by Openizer** [JerryDIT/adoptajerry#36]
TITLE pour expliciter le flowchart
"We sum up Jerry contruction process : each step of the building process has dedicated documentation made by JerryClan contributors."

Insertion des liens ci-dessous dans le flowchart 
+possibilité de télécharger PDF + commenter chaque étape

Liste des liens accessibles dans le drive
Ingrédients pour fabriquer => https://docs.google.com/document/d/1Gx3gwPejdkgPr1vq9DYgG8j2aYTKJ_c-LW5toEf0Mm8/edit
Notice test/démontage => https://docs.google.com/document/d/1K8RJW1keTaGfnhofHDtVoUOMeSXrF2qOIdqfEzR5ZOo/edit
Demande de partenariat => https://docs.google.com/document/d/1xODyqglut6LfAsYzHPd77wuny7NVdHE-NAaD5Wg9vFU/edit#heading=h.esu1ctm7q5el 
How to : cadrer le challenge ? => https://docs.google.com/document/d/1FK7U05x9lQ4MMZBHYKF4glPKzlz_Pxq2wlqepM7ryck/edit#heading=h.v1chnkvm82gx
Scrum => https://docs.google.com/presentation/d/1WEvVWe1FYlIZen0v6WFrfr7t77e-eXj8AQRtk355jr0/edit#slide=id.g66829d2fe_0_1
Organisation atelier
Fabriquer Jerry computer
Scrum
Manuel deco ? Justine ?
Comment prendre en photo ?
Formulaire bien cet atelier Jerry ?

**Comment by Openizer** [comment]
je ne vois ce mail que maintenant, qu'est ce que c'est ? :)

2015-09-17 16:04 GMT+02:00 Sébastien Bourdu <notifications@github.com>:

> Closed #36 <https://github.com/JerryDIT/adoptajerry/issues/36> via d403dcb
> <https://github.com/JerryDIT/adoptajerry/commit/d403dcbf97ef903dccc53a01c9896fee66efb866>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JerryDIT/adoptajerry/issues/36#event-412133811>.
>



-- 
Best regards,
Romain Chanut
+336 211 067 00
http://about.me/romidea

**Comment by ekkans** [comment]
@Openizer – c'est juste un mail qui indique que j'ai fermé l'*issue* : )
